---
# This playbook used 3 modules i.e., yum, service and copy
- name: Deploy httpd 
  hosts: webhosts
  tasks:
  - name: Install httpd
    yum: name=httpd
  - name: Enable httppd
    service: name=httpd enabled=true state=stopped
  - name: Create Readme File
    copy:
      content: "Welcome to httpd on webhosts!\n"
      dest: /var/log/myhttpd.README
      force: no
      mode: 0444
...
