---
# This playbook used 3 modules i.e., yum, service and copy
- name: Deploy httpd 
  hosts: webhosts
  # We can see, tasks is in form of Arrays. It has 3 arrays here, all start with a "-".
  tasks:
  - name: Install httpd
    package: name=httpd state=present
  - name: Enable httppd
    # Here arcuments to module "service" are name, enable and state
    service: name=httpd enabled=true state=stopped
  - name: Create Readme File
    copy:
      # Here arguments to module "copy" are "content, dest, etc"
      # So, we can see, arguments can be given using "=" or ":" but when we use ":", they are on separate lines with indentation of 2 spaces.
      content: "Welcome to httpd on webhosts!\n"
      dest: /var/log/myhttpd.README
      force: no
      mode: 0444
...
