---
  - name: Install httpd
    yum: 
      name:
        - "{{ web_package }}"
      state: latest
  - name: Start and Enable httppd
    # Here arcuments to module "service" are name, enable and state
    service: 
      name: "{{ web_package }}" 
      enabled: true 
      state: started
  - name: Create Readme File
    copy:
      # Here arguments to module "copy" are "content, dest, etc"
      # Arguments can be given using "=" or ":". We use ":" when on separate lines with indentation of 2 spaces.
      content: "Welcome to httpd on webhosts!\n"
      dest: /var/log/myhttpd.README
      force: no
      mode: 0444
...
